version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sinicnet123456
    ports:
      - 3306:3306
    volumes:
      - /e/docker/web_server/data/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /e/docker/web_server/data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /e/docker/web_server/data/mysql/log:/var/log/mysql #日志文件挂载
    networks:
      - web-net
  website:
    image: web_server:v1
    container_name: website
    command: bash /root/start.sh
    tty: true
    volumes:
      - /e/docker/web_server/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /e/docker/web_server/data/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /e/docker/web_server/data/nginx/conf.d/emi-ai.conf:/etc/nginx/conf.d/emi-ai.conf
      - /e/work/git:/var/pbx
      - /e/work/git/AICall:/var/pbx/website
      - /e/work/git/tmp:/var/pbx/tmp
      - /e/work/git/upload:/var/pbx/upload
      - /e/work/git/emi-ai:/var/pbx/emi-ai
    links:
      - mysql:db
    ports:
      - 80:80
      - 8080:8080
      - 6379:6379
      - 60379:60379
    networks:
      - web-net
networks: 
  web-net:
